### ISSUE TITLE
Advanced search functionality

### ISSUE THREAD

**Issue by sschlitz** [gsbodine/omeka-bootstrap#10]
- see: items/advanced-search
- this functionality is not working when searching for multiple tags
- Add search by Recipient
- Add search by Script Type
- Remove search  by public/non-public
- Remove search by user
- Remove search by featured/non-featured

**Comment by sschlitz** [comment]
Need to return a message when search term(s) have no hits & to return user to the advanced search page

**Comment by gsbodine** [comment]
We should also check to see if there is work on a more powerful search engine that would allow administrators to alias or provide 'near-hit', alternate spelling, etc., kinds of information.

**Comment by gsbodine** [comment]
Omeka 2.0 massively changed the way search is handled, so now all the comments above are moot, but this issue is not.

**Comment by sschlitz** [comment]
Functionality not working: Search entire site text, including simple pages, other web pages, etc. as well as item- and collection-level content. To clarify: text from site content as well as items, etc. should be searchable from the main page Search field as well as in the keyword field on Advanced Search.

**Comment by gsbodine** [comment]
I'm closing this since most of the styling is done for the moment -- at least until I get the other plugins' search hooks updated to match. I'm creating tickets on gsbodine/crowd-ed for that.
