### ISSUE TITLE
Browse By Tag improvements

### ISSUE THREAD

**Issue by gsbodine** [gsbodine/omeka-bootstrap#2]
display in alpha order AND chunked into smaller alphabetized sections with dropdown menu listing tags for each letter or series of letters, e.g. A-C, D-G, etc. (see http://twitter.github.com/bootstrap/javascript.html#dropdowns)

**Comment by gsbodine** [comment]
There should be more than one way to view the tags, both in cloud-tag form, alphabetized (paged with tabs?), maybe with counts or something?

**Comment by sschlitz** [comment]
I'm thinking an tag alpha index: AB, CD, EF, etc. There are lots of tags, and the list _will continue to grow_. The tag cloud is a nice visual but ungainly for users, so i think an alpha index will be easier to nav; maybe use: http://twitter.github.com/bootstrap/javascript.html#dropdowns
