### ISSUE TITLE
Home Page mouseover text

### ISSUE THREAD

**Issue by sschlitz** [gsbodine/omeka-bootstrap#3]
See http://148.137.66.219/; the mouseover text on Participate displays left, though the text for Browse and Search displays right. Can the Participate mouseover text disply right?

**Comment by gsbodine** [comment]
This is fully configurable now through the simple-pages administrator. We can do it however you'd like ;)

**Comment by sschlitz** [comment]
re: _We can do it however you'd like ;)_

I have some interesting ideas...
